### ISSUE TITLE
Update to Python 3.11

### ISSUE THREAD

**Issue by gaganpreet** [gaganpreet/fastapi-starter#479]

**Comment by vaibhavmishra4g** [comment]
heyy could you pls explain the issue? I'm interested in doing it.

**Comment by gaganpreet** [comment]
> heyy could you pls explain the issue? I'm interested in doing it.

Thanks for volunteering! You can look at this PR for Python 3.10 for inspiration: https://github.com/gaganpreet/fastapi-starter/pull/223/files.

**Comment by javi-aranda** [comment]
Hello, I made a small PR to address this issue: https://github.com/gaganpreet/fastapi-starter/pull/707
